#pragma once
#include "core/core.hpp"
#include "math/math.hpp"
#include "common/common.hpp"
#include "audio/audio.hpp"
#include "event/event.hpp"
#include "graphics/graphics.hpp"
#include "image/image.hpp"
#include "physics/physics.hpp"
#include "sync/sync.hpp"
#include "window/window.hpp"
#include "plugin/plugin.hpp"
#include "model/model.hpp"
#include "event/event.hpp"
#include "device/device.hpp"
#include "debug/debug.hpp"
#include <entt/entt.hpp>
#include <glm/glm.hpp>
#include "SDL3/SDL.h"
#include "misc/cpp/imgui_stdlib.h" // ImGui::InputText overload for std::string
#include <imgui.h>
#include <imgui_impl_sdl3.h>
#include <imgui_impl_vulkan.h>
